[package]
name = "space_kitty"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.10.1", features = ["dynamic_linking"] }
bevy_egui = "0.20.3"
bevy-inspector-egui = "0.18.3"
bevy_rapier2d = "0.21.0"
bevy_hanabi = { git = "https://github.com/djeedai/bevy_hanabi.git"}
bevy_tweening = "0.7.0"
rand = "0.8.5"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

# [package]
# name = "Balls"
# version = "0.0.1"
# description = "Just game"

# [package.metadata.bundle]
# name = "Balls Game"
# identifier = "com.ghashy.balls"
# icon = ["32x32.png", "128x128.png", "128x128@2x.png"]
# version = "0.0.1"
# resources = ["assets"]
# copyright = "Copyright (c) Ghashy. All rights reserved."
# category = "Games"
# short_description = "Just balls game"
# long_description = """
# Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
# eiusmod tempor incididunt ut labore et dolore magna aliqua.  Ut
# enim ad minim veniam, quis nostrud exercitation ullamco laboris
# nisi ut aliquip ex ea commodo consequat.
# """
# osx_url_schemes = ["com.ghashy.balls"]

# [package.metadata.bundle.bin.balls]

# [[bin]]
# name = "balls"
# path = "balls/src/main.rs"